{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    app.kubernetes.io/name: {{ include "envnexus.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                {{- if eq .backend "platform-api" }}
                name: {{ $.Release.Name }}-platform-api
                port:
                  number: {{ $.Values.service.platformApi.port }}
                {{- else if eq .backend "session-gateway" }}
                name: {{ $.Release.Name }}-session-gateway
                port:
                  number: {{ $.Values.service.sessionGateway.port }}
                {{- else if eq .backend "console-web" }}
                name: {{ $.Release.Name }}-console-web
                port:
                  number: {{ $.Values.service.consoleWeb.port }}
                {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
