{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app.kubernetes.io/name: {{ include "envnexus.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  database-dsn: "{{ .Values.mysql.auth.username }}:{{ .Values.mysql.auth.password }}@tcp({{ .Release.Name }}-mysql:3306)/{{ .Values.mysql.auth.database }}?charset=utf8mb4&parseTime=True&loc=Local"
  redis-addr: "{{ .Release.Name }}-redis-master:6379"
  jwt-secret: {{ .Values.env.ENX_JWT_SECRET | quote }}
  device-secret: {{ .Values.env.ENX_DEVICE_SECRET | quote }}
  session-secret: {{ .Values.env.ENX_SESSION_SECRET | quote }}
{{- end }}
