package watchlist

import "time"

func BuiltinRules() []*WatchItem {
	return []*WatchItem{
		{
			ID:          "builtin_net_001",
			Name:        "NET-001: DNS Resolution",
			Description: "Check DNS resolution is working by resolving a well-known domain",
			Source:      SourceBuiltin,
			ToolName:    "dns_lookup",
			ToolParams:  map[string]interface{}{"domain": "dns.google"},
			Condition: WatchCondition{
				Type: CondReachable,
			},
			Interval: 5 * time.Minute,
			Enabled:  true,
		},
		{
			ID:          "builtin_net_002",
			Name:        "NET-002: Internet Connectivity",
			Description: "Check internet connectivity by pinging a reliable endpoint",
			Source:      SourceBuiltin,
			ToolName:    "ping_host",
			ToolParams:  map[string]interface{}{"host": "8.8.8.8", "count": 3},
			Condition: WatchCondition{
				Type: CondReachable,
			},
			Interval: 5 * time.Minute,
			Enabled:  true,
		},
		{
			ID:          "builtin_sec_001",
			Name:        "SEC-001: Firewall Status",
			Description: "Verify the system firewall is active",
			Source:      SourceBuiltin,
			ToolName:    "firewall_status",
			ToolParams:  map[string]interface{}{},
			Condition: WatchCondition{
				Type:      CondCustom,
				JSONPath:  "enabled",
				Operator:  OpEQ,
				Threshold: "true",
			},
			Interval: 10 * time.Minute,
			Enabled:  true,
		},
		{
			ID:          "builtin_sec_002",
			Name:        "SEC-002: Listening Ports",
			Description: "Monitor for unexpected listening ports",
			Source:      SourceBuiltin,
			ToolName:    "list_ports",
			ToolParams:  map[string]interface{}{},
			Condition: WatchCondition{
				Type:      CondThreshold,
				JSONPath:  "count",
				Operator:  OpGT,
				Threshold: float64(100),
			},
			Interval: 15 * time.Minute,
			Enabled:  true,
		},
		{
			ID:          "builtin_perf_001",
			Name:        "PERF-001: Disk Usage",
			Description: "Alert when disk usage exceeds 90%",
			Source:      SourceBuiltin,
			ToolName:    "disk_usage",
			ToolParams:  map[string]interface{}{},
			Condition: WatchCondition{
				Type:      CondThreshold,
				JSONPath:  "usage_percent",
				Operator:  OpGT,
				Threshold: float64(90),
			},
			Interval: 10 * time.Minute,
			Enabled:  true,
		},
		{
			ID:          "builtin_perf_002",
			Name:        "PERF-002: Memory Usage",
			Description: "Alert when memory usage exceeds 90%",
			Source:      SourceBuiltin,
			ToolName:    "read_system_info",
			ToolParams:  map[string]interface{}{},
			Condition: WatchCondition{
				Type:      CondThreshold,
				JSONPath:  "memory.used_percent",
				Operator:  OpGT,
				Threshold: float64(90),
			},
			Interval: 5 * time.Minute,
			Enabled:  true,
		},
		{
			ID:          "builtin_dep_001",
			Name:        "DEP-001: Package Manager Health",
			Description: "Verify system package manager is functional",
			Source:      SourceBuiltin,
			ToolName:    "shell_exec",
			ToolParams:  map[string]interface{}{"command": "echo ok"},
			Condition: WatchCondition{
				Type: CondReachable,
			},
			Interval: 30 * time.Minute,
			Enabled:  true,
		},
		{
			ID:          "builtin_svc_001",
			Name:        "SVC-001: Critical Services",
			Description: "Check that critical system services are running",
			Source:      SourceBuiltin,
			ToolName:    "list_services",
			ToolParams:  map[string]interface{}{},
			Condition: WatchCondition{
				Type: CondReachable,
			},
			Interval: 10 * time.Minute,
			Enabled:  true,
		},
		{
			ID:          "builtin_cert_001",
			Name:        "CERT-001: TLS Certificate Expiry",
			Description: "Check TLS certificate expiry for localhost HTTPS services",
			Source:      SourceBuiltin,
			ToolName:    "check_tls",
			ToolParams:  map[string]interface{}{"host": "localhost", "port": 443},
			Condition: WatchCondition{
				Type:      CondThreshold,
				JSONPath:  "days_until_expiry",
				Operator:  OpLT,
				Threshold: float64(30),
			},
			Interval: 60 * time.Minute,
			Enabled:  true,
		},
	}
}
